namespace HomeInventory.Client;

public sealed record PropertyDto(Guid Id, string Name, string? Address, DateOnly? PurchaseDate, decimal? PurchasePrice, decimal? FloorArea, string? Notes, string Currency = "USD");
public sealed record FloorDto(Guid Id, Guid PropertyId, string Name, string? Notes);
public sealed record RoomDto(Guid Id, Guid FloorId, string Name, string? Type, decimal? Area, decimal? Volume, decimal? CeilingHeight, decimal? Length, decimal? Width, decimal? Height, string? Flooring, string? WallFinish, string? CeilingFinish, string? PaintDetails, int? WindowsCount, int? DoorsCount, string? FixturesNotes, string? UtilitiesNotes, string? Notes);
public sealed record SurfaceDto(Guid Id, Guid RoomId, string Name, string SurfaceType, string? PaintBrand, string? ColorName, string? ColorCode, string? Finish, int? Coats, DateOnly? PaintedDate, string? Painter, decimal? QuantityPurchased, string? Manufacturer, string? ProductName, string? Material, string? Supplier, string? Warranty, string? Invoice, DateOnly? InstallationDate, string? Notes, int SortOrder);
public sealed record FixtureDto(Guid Id, Guid RoomId, string Name, string Type, string? Manufacturer, string? Model, string? SerialNumber, DateOnly? PurchaseDate, decimal? PurchasePrice, decimal? CurrentValue, string? Warranty, string? ManualUrl, string? InstallerName, DateOnly? InstallationDate, string? Condition, string? Notes, string? LocationPath, string Category = "Fixture", string? Provider = null, string? AccountNumber = null);
public sealed record FixturePhotoDto(Guid Id, string StorageKey, string? Caption, int SortOrder);
public sealed record PhotoMetadataDto(Guid Id, string StorageKey, string? Caption, int SortOrder);
public sealed record PaintDto(Guid Id, string Brand, string ColorName, string? ColorCode, string? Finish, string? Notes);
public sealed record PaintUsageDto(Guid RoomId, string RoomPath, string? Surface, string Source);
public sealed record RoomPaintDto(Guid PaintId, string Brand, string ColorName, string? ColorCode, string? Finish, string? Notes, int SortOrder, string? Surface);
public sealed record StorageLocationDto(Guid Id, Guid PropertyId, Guid? ParentId, string Name, string? Type, string Path);
public sealed record AssetDto(Guid Id, Guid PropertyId, Guid? RoomId, Guid? StorageLocationId, string Name, string Category, string? Description, string? Brand, string? Model, string? SerialNumber, DateOnly? PurchaseDate, decimal? PurchasePrice, decimal? CurrentValue, string? Condition, string? Notes, bool IsArchived, string? LocationPath, string? Barcode = null, string? ManualUrl = null);
public sealed record AssetEventDto(Guid Id, Guid AssetId, DateOnly OccurredOn, string Kind, string? Description, decimal? Cost);
public sealed record AssetPhotoDto(Guid Id, string StorageKey, string? Caption, int SortOrder);
public sealed record DashboardDto(int AssetCount, int FixtureCount, IReadOnlyList<CurrencyTotalDto> Totals, int MaintenanceOverdue = 0, int MaintenanceDueSoon = 0, int WarrantiesExpiring = 0, int AssetsMissingReceipts = 0, IReadOnlyList<RecentPurchaseDto>? RecentPurchases = null, int RoomCompletionPercent = 0, int RoomsComplete = 0, int RoomCount = 0);
public sealed record RecentPurchaseDto(Guid Id, string Name, string Category, DateOnly PurchaseDate, decimal? PurchasePrice, string Currency);
public sealed record RoomCompletionDto(Guid RoomId, string RoomPath, int Score, int MaxScore, IReadOnlyList<string> Missing);
public sealed record InsuranceReportDto(DateOnly GeneratedOn, IReadOnlyList<InsurancePropertyDto> Properties);
public sealed record InsurancePropertyDto(Guid Id, string Name, string? Address, string Currency, decimal AssetTotal, decimal FixtureTotal, IReadOnlyList<CategoryTotalDto> Categories, IReadOnlyList<InsuranceItemDto> Items);
public sealed record InsuranceItemDto(string Kind, string Name, string Category, string? BrandModel, string? SerialNumber, DateOnly? PurchaseDate, decimal? PurchasePrice, decimal? CurrentValue, string? Location, int PhotoCount, bool HasReceipt);
public sealed record ContactDto(Guid Id, string Name, string? Company, string Kind, string? Phone, string? Email, string? Website, string? Notes);
/// <summary>Values already in use, offered as suggestions in free-text fields.</summary>
public sealed record LookupsDto(IReadOnlyList<string> AssetCategories, IReadOnlyList<string> Brands, IReadOnlyList<string> ContactNames);
public sealed record NetworkStatusDto(bool Enabled, int Port, bool HasPin, bool ListeningOnNetwork, IReadOnlyList<string> Addresses, bool RestartRequired);
public sealed record NetworkSettingsInput(bool Enabled, string? Pin, int? Port);
public sealed record BarcodeResultDto(string Text, string Format);
public sealed record AssistantStatusDto(bool Enabled);
public sealed record ReceiptLineDto(string Description, decimal? Quantity, decimal? Price);
public sealed record ReceiptReadDto(string? Merchant, DateOnly? PurchaseDate, decimal? Total, string? Currency, IReadOnlyList<ReceiptLineDto> Items, int? WarrantyMonths, string Summary);
public sealed record ApplyReceiptInput(ReceiptReadDto Receipt, bool UpdateAsset);
public sealed record AssetSuggestionDto(string Name, string Category, string? Brand, string? Model, string? Description, decimal? EstimatedValue, string Confidence);
public sealed record UploadedFileDto(string StorageKey, string FileName, string ContentType, long SizeBytes);
public sealed record DocumentDto(Guid Id, Guid PropertyId, Guid? RoomId, Guid? FixtureId, Guid? AssetId, Guid? MaintenanceTaskId, string Title, string Kind, string StorageKey, string? FileName, string? ContentType, long? SizeBytes, DateOnly? DocumentDate, DateOnly? ExpiresOn, string? Tags, string? Notes, string PropertyName, string? AttachedTo);
public sealed record MaintenanceTaskDto(Guid Id, Guid PropertyId, Guid? FixtureId, string Title, int? IntervalValue, string? IntervalUnit, DateOnly? DueOn, DateOnly? LastCompletedOn, string? Supplier, decimal? EstimatedCost, string? Notes, string PropertyName, string? FixtureName, string Currency);
public sealed record MaintenanceRecordDto(Guid Id, Guid TaskId, DateOnly CompletedOn, decimal? Cost, string? Supplier, string? Notes);
public sealed record CurrencyTotalDto(string Currency, decimal TotalValue, decimal FixtureValue, IReadOnlyList<CategoryTotalDto> Categories);
public sealed record CategoryTotalDto(string Category, decimal Total);
public sealed record SearchResultDto(string Kind, Guid Id, string Title, string Detail, string? LocationPath);

public sealed record PropertyInput(string Name, string? Address, DateOnly? PurchaseDate, decimal? PurchasePrice, decimal? FloorArea, string? Notes, string? Currency = null);
public sealed record FloorInput(Guid PropertyId, string Name, string? Notes);
public sealed record RoomInput(Guid FloorId, string Name, string? Type, decimal? Area, decimal? Volume, decimal? CeilingHeight, decimal? Length, decimal? Width, decimal? Height, string? Flooring, string? WallFinish, string? CeilingFinish, string? PaintDetails, int? WindowsCount, int? DoorsCount, string? FixturesNotes, string? UtilitiesNotes, string? Notes);
public sealed record SurfaceInput(Guid RoomId, string Name, string SurfaceType, string? PaintBrand, string? ColorName, string? ColorCode, string? Finish, int? Coats, DateOnly? PaintedDate, string? Painter, decimal? QuantityPurchased, string? Manufacturer, string? ProductName, string? Material, string? Supplier, string? Warranty, string? Invoice, DateOnly? InstallationDate, string? Notes, int SortOrder);
public sealed record FixtureInput(Guid RoomId, string Name, string Type, string? Manufacturer, string? Model, string? SerialNumber, DateOnly? PurchaseDate, decimal? PurchasePrice, decimal? CurrentValue, string? Warranty, string? ManualUrl, string? InstallerName, DateOnly? InstallationDate, string? Condition, string? Notes, string? Category = null, string? Provider = null, string? AccountNumber = null);
public sealed record FixturePhotoInput(string StorageKey, string? Caption, int SortOrder);
public sealed record AssetPhotoInput(string StorageKey, string? Caption, int SortOrder);
public sealed record PhotoMetadataInput(string StorageKey, string? Caption, int SortOrder);
public sealed record PaintInput(string Brand, string ColorName, string? ColorCode, string? Finish, string? Notes);
public sealed record RoomPaintInput(Guid PaintId, int SortOrder, string? Surface);
public sealed record StorageLocationInput(Guid PropertyId, Guid? ParentId, string Name, string? Type);
public sealed record AssetInput(Guid PropertyId, Guid? RoomId, Guid? StorageLocationId, string Name, string Category, string? Description, string? Brand, string? Model, string? SerialNumber, DateOnly? PurchaseDate, decimal? PurchasePrice, decimal? CurrentValue, string? Condition, string? Notes, string? Barcode = null, string? ManualUrl = null);
public sealed record AssetEventInput(DateOnly OccurredOn, string Kind, string? Description, decimal? Cost);
public sealed record AssetMoveInput(Guid? RoomId, Guid? StorageLocationId);
public sealed record MaintenanceTaskInput(Guid PropertyId, Guid? FixtureId, string Title, int? IntervalValue, string? IntervalUnit, DateOnly? DueOn, string? Supplier, decimal? EstimatedCost, string? Notes);
public sealed record DocumentInput(Guid PropertyId, Guid? RoomId, Guid? FixtureId, Guid? AssetId, Guid? MaintenanceTaskId, string Title, string Kind, string StorageKey, string? FileName, string? ContentType, long? SizeBytes, DateOnly? DocumentDate, DateOnly? ExpiresOn, string? Tags, string? Notes);
public sealed record ContactInput(string Name, string? Company, string Kind, string? Phone, string? Email, string? Website, string? Notes);
public sealed record MaintenanceCompletionInput(DateOnly CompletedOn, decimal? Cost, string? Supplier, string? Notes);

public sealed record InventoryExport(int SchemaVersion, List<ImportProperty> Properties, List<ImportFloor> Floors, List<ImportRoom> Rooms, List<ImportSurface> Surfaces, List<ImportStorageLocation> StorageLocations, List<ImportAsset> Assets, List<ImportPropertyPhoto> PropertyPhotos, List<ImportFixture>? Fixtures = null, List<ImportAssetPhoto>? AssetPhotos = null, List<ImportPaint>? Paints = null, List<ImportRoomPaint>? RoomPaints = null, List<ImportRoomPhoto>? RoomPhotos = null, List<ImportFixturePhoto>? FixturePhotos = null, List<ImportMaintenanceTask>? MaintenanceTasks = null, List<ImportMaintenanceRecord>? MaintenanceRecords = null, List<ImportDocument>? Documents = null, List<ImportAssetEvent>? AssetEvents = null, List<ImportContact>? Contacts = null);
public sealed record ImportProperty(string ExternalId, string Name, string? Address, DateOnly? PurchaseDate, decimal? PurchasePrice, decimal? FloorArea, string? Notes, string? Currency = null);
public sealed record ImportFloor(string ExternalId, string PropertyExternalId, string Name, string? Notes);
public sealed record ImportPropertyPhoto(string ExternalId, string PropertyExternalId, string? StorageKey, string? Caption, int SortOrder);
public sealed record ImportRoom(string ExternalId, string FloorExternalId, string Name, string? Type, decimal? Area, decimal? Volume, decimal? CeilingHeight, decimal? Length, decimal? Width, decimal? Height, string? Flooring, string? WallFinish, string? CeilingFinish, string? PaintDetails, int? WindowsCount, int? DoorsCount, string? FixturesNotes, string? UtilitiesNotes, string? Notes);
public sealed record ImportSurface(string ExternalId, string RoomExternalId, string Name, string SurfaceType, string? PaintBrand, string? ColorName, string? ColorCode, string? Finish, int? Coats, DateOnly? PaintedDate, string? Painter, decimal? QuantityPurchased, string? Manufacturer, string? ProductName, string? Material, string? Supplier, string? Warranty, string? Invoice, DateOnly? InstallationDate, string? Notes, int SortOrder);
public sealed record ImportStorageLocation(string ExternalId, string PropertyExternalId, string? ParentExternalId, string Name, string? Type);
public sealed record ImportAsset(string ExternalId, string PropertyExternalId, string? RoomExternalId, string? StorageLocationExternalId, string Name, string Category, string? Description, string? Brand, string? Model, string? SerialNumber, DateOnly? PurchaseDate, decimal? PurchasePrice, decimal? CurrentValue, string? Condition, string? Notes, string? Barcode = null, string? ManualUrl = null);
public sealed record ImportFixture(string ExternalId, string RoomExternalId, string Name, string Type, string? Manufacturer, string? Model, string? SerialNumber, DateOnly? PurchaseDate, decimal? PurchasePrice, decimal? CurrentValue, string? Warranty, string? ManualUrl, string? InstallerName, DateOnly? InstallationDate, string? Condition, string? Notes, string? Category = null, string? Provider = null, string? AccountNumber = null, string? MaintenanceSchedule = null, DateOnly? LastMaintenanceDate = null);
public sealed record ImportAssetPhoto(string ExternalId, string AssetExternalId, string? StorageKey, string? Caption, int SortOrder);
public sealed record ImportPaint(string ExternalId, string Brand, string ColorName, string? ColorCode, string? Finish, string? Notes);
public sealed record ImportRoomPaint(string ExternalId, string RoomExternalId, string PaintExternalId, int SortOrder, string? Surface);
public sealed record ImportRoomPhoto(string ExternalId, string RoomExternalId, string? StorageKey, string? Caption, int SortOrder);
public sealed record ImportFixturePhoto(string ExternalId, string FixtureExternalId, string? StorageKey, string? Caption, int SortOrder);
public sealed record ImportMaintenanceTask(string ExternalId, string PropertyExternalId, string? FixtureExternalId, string Title, int? IntervalValue, string? IntervalUnit, DateOnly? DueOn, DateOnly? LastCompletedOn, string? Supplier, decimal? EstimatedCost, string? Notes);
public sealed record ImportMaintenanceRecord(string ExternalId, string TaskExternalId, DateOnly CompletedOn, decimal? Cost, string? Supplier, string? Notes);
public sealed record ImportDocument(string ExternalId, string PropertyExternalId, string? RoomExternalId, string? FixtureExternalId, string? AssetExternalId, string? MaintenanceTaskExternalId, string Title, string Kind, string StorageKey, string? FileName, string? ContentType, long? SizeBytes, DateOnly? DocumentDate, DateOnly? ExpiresOn, string? Tags, string? Notes);
public sealed record ZipImportDto(InventoryExport Inventory, int FilesRestored, int FilesSkipped);
public sealed record ImportAssetEvent(string ExternalId, string AssetExternalId, DateOnly OccurredOn, string Kind, string? Description, decimal? Cost);
public sealed record ImportContact(string ExternalId, string Name, string? Company, string Kind, string? Phone, string? Email, string? Website, string? Notes);
public sealed record ImportPreviewDto(bool IsValid, IReadOnlyList<string> Errors, int Properties, int Floors, int Rooms, int Surfaces, int StorageLocations, int Assets, IReadOnlyList<string> DuplicateExternalIds, int Fixtures = 0, int Paints = 0, int Photos = 0, int ExistingRecords = 0, int MaintenanceTasks = 0, int Documents = 0);
